FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./www /app

RUN apt-get update && apt-get install -y --no-install-recommends \
   libmariadb-dev-compat gcc pkg-config \
&& rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mysqlclient

EXPOSE 8000