FROM python:3.13.2-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./www /app

RUN python manage.py collectstatic --noinput
RUN python manage.py migrate

EXPOSE 8080

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "TheKaijeawProject.asgi:application"]