services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.django
    container_name: django_app
    command: "daphne -b 0.0.0.0 -p 8000 TheKaijeawProject.asgi:application"
    volumes:
      - ./www:/app
      - ./staticfiles:/app/staticfiles
    restart: always
  nginx:
    image: nginx:latest
    container_name: django_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

volumes:
  static_volume: