# Generated by Django 5.1.6 on 2025-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='amount',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='egg',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='queue_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
