# Generated by Django 5.1.6 on 2025-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_egg_amount_alter_egg_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_fillings',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='queue_capacity',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
