# Generated by Django 5.1.7 on 2025-03-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_restaurant_max_fillings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='egg_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.egg'),
        ),
    ]
