# Generated by Django 5.1.7 on 2025-04-02 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def add_restaurant(apps, schema_editor):
    Model = apps.get_model('app', 'Restaurant')
    Model.objects.create()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('amount', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-z_]+$', 'Only a-z, A-Z and Underscore ( _ ) characters are allowed')])),
                ('title', models.TextField(default='Untitled')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_capacity', models.PositiveSmallIntegerField(default=20)),
                ('max_fillings', models.PositiveSmallIntegerField(default=3)),
                ('is_opened', models.BooleanField(default=False)),
                ('allow_takeaway', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_takeaway', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('egg_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.egg')),
                ('fillings', models.ManyToManyField(blank=True, to='app.filling')),
            ],
        ),
        migrations.RunPython(add_restaurant)
    ]
