# Generated by Django 5.1.7 on 2025-03-30 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_egg_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-z_]+$', 'Only a-z, A-Z and Underscore (_) characters are allowed')]),
        ),
    ]
