# Generated by Django 5.1.6 on 2025-02-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('amount', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField(default='Untitled')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_capacity', models.IntegerField()),
                ('is_opened', models.BooleanField(default=False)),
                ('allow_takeaway', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_takeaway', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('egg_amount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.egg')),
                ('fillings', models.ManyToManyField(blank=True, to='orders.filling')),
            ],
        ),
    ]
