# Generated by Django 5.1.6 on 2025-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_capacity', models.IntegerField()),
                ('is_opened', models.BooleanField(default=False)),
                ('passcode', models.CharField(max_length=128)),
                ('allow_takeaway', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='fillings',
            field=models.ManyToManyField(blank=True, to='orders.filling'),
        ),
    ]
